# Generated by Django 3.1.3 on 2020-11-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20201120_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.ManyToManyField(blank=True, null=True, to='teacher.Class'),
        ),
    ]
