# Generated by Django 3.1.3 on 2020-11-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20201123_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_class',
            field=models.ManyToManyField(blank=True, to='teacher.Class'),
        ),
    ]
