# Generated by Django 3.1.3 on 2020-12-07 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0016_auto_20201207_1115'),
        ('teacher', '0008_auto_20201129_1248'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
