# Generated by Django 3.1.3 on 2020-12-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_requestforjoiningtoschool'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
