# Generated by Django 3.1.3 on 2020-12-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_teacher_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='free_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
