# Generated by Django 3.1.3 on 2021-01-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_auto_20201226_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='free_trial',
        ),
        migrations.AddField(
            model_name='school',
            name='free_trial_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='key',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='free_trial_up',
            field=models.BooleanField(default=False),
        ),
    ]
