# Generated by Django 3.1.3 on 2021-01-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0014_auto_20210104_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='key',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
