# Generated by Django 3.1.3 on 2021-01-04 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0020_auto_20210104_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_headmaster',
        ),
    ]
