# Generated by Django 3.1.3 on 2021-01-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0021_remove_teacher_is_headmaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_headmaster',
            field=models.BooleanField(default=False),
        ),
    ]
