# Generated by Django 3.1.3 on 2021-01-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0023_auto_20210104_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_headmaster',
        ),
    ]
