# Generated by Django 3.1.3 on 2021-01-22 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0027_auto_20210123_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestForJoiningToSchool',
        ),
    ]
