# Generated by Django 3.1.3 on 2021-01-22 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0028_delete_requestforjoiningtoschool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='access_key',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='free_trial_up',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_paid',
        ),
    ]
