# Generated by Django 3.1.3 on 2021-01-23 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0030_bell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='key',
        ),
    ]
