# Generated by Django 3.1.3 on 2021-01-23 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0033_auto_20210123_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='max_members',
        ),
        migrations.AddField(
            model_name='class',
            name='school_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.schoolyear'),
        ),
    ]
