# Generated by Django 3.1.3 on 2021-01-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0034_auto_20210123_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='schoolyear',
            name='start',
            field=models.DateField(null=True),
        ),
    ]
