# Generated by Django 3.1.3 on 2021-02-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0036_class_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
