# Generated by Django 3.1.3 on 2021-02-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0039_auto_20210203_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtemplate',
            name='subjects_1',
            field=models.ManyToManyField(blank=True, to='teacher.Subject'),
        ),
    ]
