# Generated by Django 3.1.3 on 2021-02-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0040_classtemplate_subjects_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtemplate',
            name='subjects_2',
            field=models.ManyToManyField(blank=True, related_name='subjects2', to='teacher.Subject'),
        ),
        migrations.AlterField(
            model_name='classtemplate',
            name='subjects_1',
            field=models.ManyToManyField(blank=True, related_name='subjects1', to='teacher.Subject'),
        ),
    ]
