# Generated by Django 3.1.3 on 2021-02-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0041_auto_20210203_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtemplate',
            name='subjects_3',
            field=models.ManyToManyField(blank=True, related_name='subjects3', to='teacher.Subject'),
        ),
        migrations.AddField(
            model_name='classtemplate',
            name='subjects_4',
            field=models.ManyToManyField(blank=True, related_name='subjects4', to='teacher.Subject'),
        ),
        migrations.AddField(
            model_name='classtemplate',
            name='subjects_5',
            field=models.ManyToManyField(blank=True, related_name='subjects5', to='teacher.Subject'),
        ),
        migrations.AddField(
            model_name='classtemplate',
            name='subjects_6',
            field=models.ManyToManyField(blank=True, related_name='subjects6', to='teacher.Subject'),
        ),
        migrations.AddField(
            model_name='classtemplate',
            name='subjects_7',
            field=models.ManyToManyField(blank=True, related_name='subjects7', to='teacher.Subject'),
        ),
        migrations.AddField(
            model_name='classtemplate',
            name='subjects_8',
            field=models.ManyToManyField(blank=True, related_name='subjects8', to='teacher.Subject'),
        ),
    ]
