# Generated by Django 3.1.3 on 2021-02-03 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0042_auto_20210203_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtemplate',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.school'),
        ),
    ]
