# Generated by Django 3.1.3 on 2021-02-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0084_auto_20210203_1454'),
        ('teacher', '0045_auto_20210203_1607'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='SchoolClass',
        ),
    ]
