# Generated by Django 3.1.3 on 2021-02-03 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0046_auto_20210203_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='related_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.schoolclass'),
        ),
    ]
