# Generated by Django 3.1.3 on 2021-02-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0047_auto_20210203_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='related_class',
        ),
        migrations.AddField(
            model_name='group',
            name='related_classes',
            field=models.ManyToManyField(to='teacher.SchoolClass'),
        ),
    ]
