# Generated by Django 3.1.3 on 2021-02-08 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0048_auto_20210205_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(max_length=1)),
                ('bell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.bell')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.group')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
