# Generated by Django 3.1.3 on 2021-02-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0049_scheduleelement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleelement',
            name='day_of_week',
            field=models.IntegerField(),
        ),
    ]
