# Generated by Django 3.1.3 on 2021-02-08 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0050_auto_20210208_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleelement',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher'),
        ),
    ]
