# Generated by Django 3.1.3 on 2021-02-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0054_auto_20210209_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Replacement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bell', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.bell')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.group')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher')),
            ],
        ),
    ]
