# Generated by Django 3.1.3 on 2021-02-10 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0055_auto_20210210_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='replacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.replacement'),
        ),
    ]
