# Generated by Django 3.1.3 on 2021-02-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0059_auto_20210210_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='replacement',
            name='bell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.bell'),
        ),
        migrations.AddField(
            model_name='replacement',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.group'),
        ),
    ]
