# Generated by Django 3.1.3 on 2021-02-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0060_auto_20210210_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replacement',
            name='schedule_element',
        ),
    ]
