# Generated by Django 3.1.3 on 2021-02-10 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0061_remove_replacement_schedule_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replacement',
            name='bell',
        ),
        migrations.RemoveField(
            model_name='replacement',
            name='group',
        ),
        migrations.AddField(
            model_name='replacement',
            name='schedule_element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.scheduleelement'),
        ),
    ]
