# Generated by Django 3.1.3 on 2021-02-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0064_auto_20210210_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
