# Generated by Django 3.1.3 on 2021-02-17 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0065_lesson_is_canceled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_absent', models.BooleanField(default=False)),
                ('is_late', models.BooleanField(default=False)),
                ('is_exempt', models.BooleanField(default=False)),
                ('excuse', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.schoolterm')),
            ],
        ),
    ]
