# Generated by Django 3.1.3 on 2021-02-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0099_auto_20210221_1909'),
        ('teacher', '0067_auto_20210218_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=3, null=True)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, default=0, null=True)),
                ('include_in_mean', models.BooleanField(default=True)),
                ('mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.gradetemplate')),
                ('school_term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.schoolterm')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.student')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher')),
                ('test', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=2)),
                ('is_predicted', models.BooleanField(default=False)),
                ('is_annual', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.student')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.subject')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.schoolterm')),
            ],
        ),
    ]
