# Generated by Django 3.1.3 on 2021-02-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0068_finalgrade_grade_gradetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='grades',
            field=models.ManyToManyField(to='teacher.GradeTemplate'),
        ),
    ]
