# Generated by Django 3.1.3 on 2021-02-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0071_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_graduate',
            field=models.BooleanField(default=False),
        ),
    ]
