# Generated by Django 3.1.3 on 2021-03-01 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0072_student_is_graduate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequency',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.student'),
        ),
        migrations.CreateModel(
            name='RequestForExcuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_rejected', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('frequency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teacher.frequency')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.parent')),
            ],
        ),
    ]
