# Generated by Django 3.1.3 on 2021-03-01 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0073_auto_20210301_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestforexcuse',
            name='frequency',
        ),
        migrations.AddField(
            model_name='requestforexcuse',
            name='frequency',
            field=models.ManyToManyField(to='teacher.Frequency'),
        ),
    ]
