# Generated by Django 3.1.3 on 2021-03-08 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0076_auto_20210302_0959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('color', models.CharField(max_length=7)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('schedule_element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.scheduleelement')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
