# Generated by Django 3.1.3 on 2021-03-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0077_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleelement',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='scheduleelement',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
