# Generated by Django 3.1.3 on 2021-03-25 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0080_auto_20210321_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_admin',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_teacher',
            field=models.BooleanField(null=True),
        ),
    ]
