# Generated by Django 3.1.3 on 2021-04-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0083_auto_20210408_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleelement',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scheduleelement',
            name='start_date',
            field=models.DateTimeField(null=True),
        ),
    ]
