# Generated by Django 3.1.3 on 2021-04-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0085_auto_20210408_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestforexcuse',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
