# Generated by Django 3.1.3 on 2021-05-02 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0086_requestforexcuse_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.school'),
        ),
    ]
