# Generated by Django 3.1.3 on 2021-01-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directmessages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='slug',
            field=models.SlugField(default='ALM0iRMLG2yHBLqjgegsKTUHi1BV6ZPeroHCuecgpATYH', unique=True),
        ),
    ]
