# Generated by Django 3.1.3 on 2021-01-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directmessages', '0002_directmessage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
