# Generated by Django 3.1.3 on 2021-01-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directmessages', '0003_auto_20210119_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True, unique=True),
        ),
    ]
