# Generated by Django 3.1.3 on 2021-01-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0016_auto_20210104_1358'),
        ('student', '0003_auto_20210104_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ManyToManyField(to='teacher.School'),
        ),
    ]
