# Generated by Django 3.1.3 on 2021-01-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0025_auto_20210104_1513'),
        ('student', '0005_auto_20210104_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ManyToManyField(to='teacher.School'),
        ),
    ]
