# Generated by Django 3.1.3 on 2021-01-22 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0028_delete_requestforjoiningtoschool'),
        ('student', '0006_auto_20210104_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.school'),
        ),
    ]
