# Generated by Django 3.1.3 on 2021-02-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0084_auto_20210203_1454'),
        ('student', '0007_auto_20210123_0009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
