# Generated by Django 3.1.3 on 2020-11-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_auto_20201130_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='TypeOfTask',
        ),
    ]
