# Generated by Django 3.1.3 on 2020-11-30 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20201129_1248'),
        ('tests', '0005_auto_20201130_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.student'),
        ),
    ]
