# Generated by Django 3.1.3 on 2020-11-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_remove_test_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='access_key',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
