# Generated by Django 3.1.3 on 2020-11-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_task_access_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='access_key',
        ),
        migrations.RemoveField(
            model_name='test',
            name='students',
        ),
        migrations.AddField(
            model_name='test',
            name='access_key',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
