# Generated by Django 3.1.3 on 2020-11-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20201130_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='access_key',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
