# Generated by Django 3.1.3 on 2020-11-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_auto_20201129_1248'),
        ('tests', '0011_auto_20201130_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='access_key',
        ),
        migrations.AddField(
            model_name='test',
            name='students',
            field=models.ManyToManyField(to='teacher.Class'),
        ),
    ]
