# Generated by Django 3.1.3 on 2020-12-01 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.task'),
        ),
    ]
