# Generated by Django 3.1.3 on 2020-12-07 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_auto_20201207_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
