# Generated by Django 3.1.3 on 2020-12-07 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0024_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='students_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test'),
        ),
    ]
