# Generated by Django 3.1.3 on 2020-12-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0025_task_students_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='students_test',
        ),
        migrations.AddField(
            model_name='task',
            name='students_test',
            field=models.ManyToManyField(null=True, to='tests.Test'),
        ),
    ]
