# Generated by Django 3.1.3 on 2020-12-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0028_test_blank_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
