# Generated by Django 3.1.3 on 2020-12-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0030_auto_20201211_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blanktest',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
