# Generated by Django 3.1.3 on 2020-12-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0031_auto_20201211_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='earned_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
