# Generated by Django 3.1.3 on 2020-12-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0032_auto_20201215_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
