# Generated by Django 3.1.3 on 2020-12-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0034_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='blanktest',
            name='autocheck',
            field=models.BooleanField(default=False),
        ),
    ]
