# Generated by Django 3.1.3 on 2020-12-15 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0035_blanktest_autocheck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
