# Generated by Django 3.1.3 on 2020-12-15 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0036_delete_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=2)),
                ('from_percent', models.IntegerField()),
                ('to_percent', models.IntegerField()),
                ('blank_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.blanktest')),
            ],
        ),
    ]
