# Generated by Django 3.1.3 on 2020-12-15 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0037_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blanktest',
            name='autocheck',
        ),
    ]
