# Generated by Django 3.1.3 on 2020-12-15 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0039_auto_20201215_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
