# Generated by Django 3.1.3 on 2020-12-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0040_auto_20201215_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='mark',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
