# Generated by Django 3.1.3 on 2020-12-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0041_test_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='is_marked',
        ),
    ]
