# Generated by Django 3.1.3 on 2020-12-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0042_remove_test_is_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
