# Generated by Django 3.1.3 on 2020-12-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0045_auto_20201223_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='blanktest',
            name='countdown',
            field=models.DurationField(null=True),
        ),
    ]
