# Generated by Django 3.1.3 on 2020-12-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0013_auto_20201226_2036'),
        ('tests', '0047_auto_20201227_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blanktest',
            name='students',
            field=models.ManyToManyField(to='teacher.Class'),
        ),
    ]
