# Generated by Django 3.1.3 on 2020-12-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0049_studentsmark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsMark',
        ),
    ]
