# Generated by Django 3.1.3 on 2020-12-31 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0050_delete_studentsmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='blanktest',
            name='allowed_exits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blanktest',
            name='are_exists_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='test',
            name='exists',
            field=models.IntegerField(default=0),
        ),
    ]
