# Generated by Django 3.1.3 on 2020-12-31 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0051_auto_20201231_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='exists',
            new_name='exits',
        ),
    ]
