# Generated by Django 3.1.3 on 2021-01-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0054_testlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='answer_options_imgs/'),
        ),
    ]
