# Generated by Django 3.1.3 on 2021-01-03 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0055_answeroption_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_option',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.answeroption'),
        ),
    ]
