# Generated by Django 3.1.3 on 2021-01-05 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0026_auto_20210105_1354'),
        ('tests', '0056_answer_answer_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blanktest',
            name='students',
        ),
        migrations.AddField(
            model_name='blanktest',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.class'),
        ),
    ]
