# Generated by Django 3.1.3 on 2021-01-05 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0057_auto_20210105_1744'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='listening/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.task')),
            ],
        ),
    ]
