# Generated by Django 3.1.3 on 2021-01-05 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0058_listening'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listening',
        ),
    ]
