# Generated by Django 3.1.3 on 2021-01-06 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0060_task_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrueFalseTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('is_correct', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.task')),
            ],
        ),
    ]
