# Generated by Django 3.1.3 on 2021-01-06 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0061_truefalsetask'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='true_false',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.truefalsetask'),
        ),
        migrations.AddField(
            model_name='truefalsetask',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='char_field',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
