# Generated by Django 3.1.3 on 2021-01-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0062_auto_20210106_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='true_false',
        ),
        migrations.AddField(
            model_name='answer',
            name='true_false',
            field=models.ManyToManyField(blank=True, null=True, to='tests.TrueFalseTask'),
        ),
    ]
