# Generated by Django 3.1.3 on 2021-01-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0063_auto_20210108_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='true_false',
            field=models.ManyToManyField(blank=True, to='tests.TrueFalseTask'),
        ),
    ]
