# Generated by Django 3.1.3 on 2021-01-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0064_auto_20210108_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='true_false',
        ),
        migrations.AddField(
            model_name='answer',
            name='true_false',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.truefalsetask'),
        ),
    ]
