# Generated by Django 3.1.3 on 2021-01-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0065_auto_20210108_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
