# Generated by Django 3.1.3 on 2021-01-09 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0026_auto_20210105_1354'),
        ('student', '0006_auto_20210104_1609'),
        ('tests', '0066_test_total_points'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mark',
            new_name='Threshold',
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=3)),
                ('category', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('weight', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher')),
                ('test', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tests.test')),
            ],
        ),
    ]
