# Generated by Django 3.1.3 on 2021-01-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0067_auto_20210109_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='category',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='grade',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='weight',
            field=models.IntegerField(blank=True),
        ),
    ]
