# Generated by Django 3.1.3 on 2021-01-09 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0026_auto_20210105_1354'),
        ('student', '0006_auto_20210104_1609'),
        ('tests', '0068_auto_20210109_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='category',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='mark',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='test',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tests.test'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
