# Generated by Django 3.1.3 on 2021-01-09 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0071_answerfortf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerfortf',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.answer'),
        ),
        migrations.AlterField(
            model_name='answerfortf',
            name='checked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answerfortf',
            name='is_correct',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='answerfortf',
            name='true_false',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.truefalsetask'),
        ),
    ]
