# Generated by Django 3.1.3 on 2021-01-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0072_auto_20210109_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerfortf',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.task'),
        ),
    ]
