# Generated by Django 3.1.3 on 2021-01-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0073_answerfortf_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
