# Generated by Django 3.1.3 on 2021-01-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0074_auto_20210109_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='blanktest',
            name='ignore_upper_case',
            field=models.BooleanField(default=True),
        ),
    ]
