# Generated by Django 3.1.3 on 2021-01-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0077_auto_20210113_1402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='total_points',
            new_name='earned_points',
        ),
    ]
