# Generated by Django 3.1.3 on 2021-01-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0078_auto_20210113_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='earned_points',
            new_name='total_points',
        ),
        migrations.AddField(
            model_name='testgroup',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
