# Generated by Django 3.1.3 on 2021-01-13 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0079_auto_20210113_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testgroup',
            name='points',
        ),
    ]
