# Generated by Django 3.1.3 on 2021-01-18 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0080_remove_testgroup_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
