# Generated by Django 3.1.3 on 2021-01-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0081_answer_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='comment',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
