# Generated by Django 3.1.3 on 2021-01-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0082_auto_20210118_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='blanktest',
            name='instruction',
            field=models.TextField(null=True),
        ),
    ]
