# Generated by Django 3.1.3 on 2021-02-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0051_auto_20210208_1826'),
        ('tests', '0084_auto_20210203_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.subject'),
        ),
    ]
