# Generated by Django 3.1.3 on 2021-02-17 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0066_frequency'),
        ('tests', '0085_grade_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='school_term',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.schoolterm'),
        ),
        migrations.AddField(
            model_name='grade',
            name='school_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.schoolyear'),
        ),
    ]
