# Generated by Django 3.1.3 on 2021-02-19 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0087_remove_grade_school_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=3, null=True)),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='grade',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.gradetemplate'),
        ),
    ]
