# Generated by Django 3.1.3 on 2021-02-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0088_auto_20210219_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='mark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.gradetemplate'),
        ),
    ]
