# Generated by Django 3.1.3 on 2021-02-19 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0090_auto_20210219_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='mark',
        ),
    ]
