# Generated by Django 3.1.3 on 2021-02-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0067_auto_20210218_1527'),
        ('tests', '0094_auto_20210219_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=2)),
                ('is_predicted', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('is_annual', models.BooleanField(default=False)),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.schoolterm')),
            ],
        ),
    ]
