# Generated by Django 3.1.3 on 2021-02-19 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0067_auto_20210218_1527'),
        ('tests', '0095_finalgrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalgrade',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.subject'),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.teacher'),
        ),
        migrations.AlterField(
            model_name='finalgrade',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.schoolterm'),
        ),
    ]
