# Generated by Django 3.1.3 on 2021-02-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0096_auto_20210219_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalgrade',
            name='is_final',
        ),
    ]
