# Generated by Django 3.1.3 on 2021-02-19 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0067_auto_20210218_1527'),
        ('tests', '0097_remove_finalgrade_is_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalgrade',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.student'),
        ),
    ]
