# Generated by Django 3.1.3 on 2021-02-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0098_finalgrade_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='school_term',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='test',
        ),
        migrations.DeleteModel(
            name='FinalGrade',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='GradeTemplate',
        ),
    ]
