# Generated by Django 3.1.3 on 2021-02-23 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0072_student_is_graduate'),
        ('tests', '0099_auto_20210221_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blanktest',
            name='students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.group'),
        ),
    ]
